services:  
  project:
    image: cloudsystemen
    build: ./Milestone2
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.project.rule=Host(`cloudsystemen.de-moor.online`)"
      - "traefik.http.routers.project.entrypoints=websecure"
      - "traefik.http.routers.project.tls.certresolver=projectresolver"
      - "traefik.http.services.project.loadbalancer.server.port=3000"
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.projectresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.projectresolver.acme.email=sanderdemoor@outlook.com"
      - "--certificatesresolvers.projectresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"