services:  
  project:
    image: my/project
    build: ./Milestone2
    volumes:  
      - "../.env:/usr/src/app/.env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.project.rule=Host(project.maesen.online)"
      - "traefik.http.routers.project.entrypoints=websecure"
      - "traefik.http.routers.project.tls.certresolver=projectresolver"
      - "../.env:/usr/src/app/.env"
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.projectresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.projectresolver.acme.email=tiwaztyr1802@gmail.com"
      - "--certificatesresolvers.projectresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "../letsencrypt:/letsencrypt"